repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: .krew/
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args:
          - --all
          - --
          - --check
          - --color
          - always
      - id: cargo-check

  - repo: local
    hooks:
      - id: clippy-check
        name: clippy-check
        description: Checks all the code for lint errors
        entry: cargo clippy --fix --no-deps --allow-dirty --allow-staged
        language: system
        pass_filenames: false
